Community
nf-core/pangenome pull request #105
Opened 2022-12-14 13:53 UTC by subwaystation

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/pangenome/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/pangenome _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-12-14 16:04 UTC, ggabernet requested changes
Hi Simon, I've added some comments in your PR already to make sure the pipeline is going the right direction in sync with the rest of nf-core pipelines

2022-12-14 16:14 UTC, subwaystation commented on Dockerfile
> +COPY bin/net2communities.py /
With the modules update, this Dockerfile will be obsolete.

2022-12-14 16:16 UTC, subwaystation commented on Dockerfile
> +COPY bin/net2communities.py /
If I remove these binaries, how can I access them outside of the Docker or Singularity?

2022-12-14 16:35 UTC, subwaystation commented on subworkflows/local/community/main.nf
> +process paf2Net {
As just discussed, I will start with local modules first.

2022-12-14 16:35 UTC, subwaystation commented on Dockerfile
> +COPY bin/net2communities.py /
As just discussed, I will have to follow `bin/markdown_to_html.py` after I created a local module for each of these python scripts.

2022-12-15 09:40 UTC, subwaystation commented on Dockerfile
> +COPY bin/net2communities.py /
I will do this in an extra PR because this one is already getting so large. I will ping you in the new one @ggabernet

2022-12-15 13:43 UTC, subwaystation commented on .github/workflows/ci.yml
> +          nextflow run ${GITHUB_WORKSPACE} -profile test,docker --n_haplotypes 12 --smoothxg_poa_length 700
Done :)

2022-12-15 14:58 UTC, merged